---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - patch
  - update
- apiGroups:
  - apps/v1
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - patch
  - update
  - watch
- apiGroups:
  - wireguard.kloudlite.github.com
  resources:
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wireguard.kloudlite.github.com
  resources:
  - servers/finalizers
  verbs:
  - update
- apiGroups:
  - wireguard.kloudlite.github.com
  resources:
  - servers/status
  verbs:
  - get
  - patch
  - update
