# This rule is not used by the project wireguard itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over wireguard.kloudlite.github.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: wireguard
    app.kubernetes.io/managed-by: kustomize
  name: server-admin-role
rules:
- apiGroups:
  - wireguard.kloudlite.github.com
  resources:
  - servers
  verbs:
  - '*'
- apiGroups:
  - wireguard.kloudlite.github.com
  resources:
  - servers/status
  verbs:
  - get
