# This rule is not used by the project wireguard itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the wireguard.kloudlite.github.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: wireguard
    app.kubernetes.io/managed-by: kustomize
  name: server-editor-role
rules:
- apiGroups:
  - wireguard.kloudlite.github.com
  resources:
  - servers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - wireguard.kloudlite.github.com
  resources:
  - servers/status
  verbs:
  - get
