# This rule is not used by the project wireguard itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to wireguard.kloudlite.github.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: wireguard
    app.kubernetes.io/managed-by: kustomize
  name: server-viewer-role
rules:
- apiGroups:
  - wireguard.kloudlite.github.com
  resources:
  - servers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - wireguard.kloudlite.github.com
  resources:
  - servers/status
  verbs:
  - get
