apiVersion: wireguard.kloudlite.github.com/v1
kind: Server
metadata:
  labels:
    app.kubernetes.io/name: wireguard
    app.kubernetes.io/managed-by: kustomize
  name: server-sample
spec:
  # TODO(user): Add fields here
