name: Release Helm Chart

on:
  workflow_call:
    inputs:
      chart_version: 
        type: string
        description: "helm chart version that this release"
        required: true

      chart_app_version: 
        type: string
        description: "helm chart appVersion for this release"
        required: true

      overwrite_release_assets:
        type: string
        description: "Should Overwrite Existing Release Assets"
        default: "false"

      charts:
        type: string
        description: "multiline string of all charts to package"
        required: true

      github_release:
        type: string
        description: "Github Release over which tarballs would be uploaded"
        required: true

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: helm release action
        uses: nxtcoder17/actions/helm-release@main
        with:
          chart_version: ${{ inputs.chart_version }}
          chart_app_version: ${{ inputs.chart_app_version }}
          overwrite_release_assets: ${{ inputs.overwrite_release_assets }}
          charts: ${{inputs.charts}}
          github_release: ${{ inputs.github_release }}
          github_token: ${{ github.token }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

